/**
 * In-memory Store — used when Postgres is unreachable (e.g. DATABASE_URL
 * incomplete). Mirrors the Postgres store's duplicate-safe upsert semantics:
 * rows are keyed by provider external IDs, so re-running syncs REPLACES rows
 * instead of duplicating. Demo data is generated by the same generator that
 * feeds the Postgres store.
 */
import {
  type AppointmentRow,
  type AttributionRow,
  type AvailabilityRule,
  type BlockedTimeRow,
  type CallRow,
  type LeadRow,
  attributionDegradation,
  createdBusinessDateOf,
} from "../metrics/compute";
import { normalizeEmail, normalizeUSPhone } from "../identity/normalize";
import type {
  AppSettings,
  AuditCallRow,
  CallContactBackfillUpdate,
  ConnectionRow,
  ContactExternalIdRow,
  ContactIdentityRow,
  ContactRow,
  DailyPrioritiesRow,
  HarvestCallRow,
  HarvestConvRow,
  HarvestProgressRow,
  LeadCountAdjustmentRow,
  ManualOverrideRow,
  MonthlyGoalRow,
  OpportunityRow,
  PipCheckinRow,
  PipCreateInput,
  PipDraftPatch,
  PipEvidenceSnapshotRow,
  PipEventRow,
  PipRow,
  PipStatus,
  PipTemplateCreateInput,
  PipTemplatePatch,
  PipTemplateRow,
  RepGoalRowFull,
  Store,
  SyncRunRow,
  TeamGoalRow,
  UserRow,
  WeeklyReportNotesRow,
  CommissionAdjustmentInput,
  CommissionAdjustmentRow,
  CommissionUpsertResult,
  CommissionAssignment,
  CommissionCycleRow,
  CommissionProfileInput,
  CommissionWeeklyRow,
} from "./types";
import { DEFAULT_CALL_START_DATES, DEFAULT_COMMISSION_PROFILES, defaultSettings, normalizeAppSettings, normalizePipActionList, parseSyncStartedMs, STALE_RUN_REAP_MINUTES } from "./types";
import {
  applyPipDraftPatch,
  assertCancelRequirements,
  assertCheckinAllowed,
  assertCompleteRequirements,
  assertIssueRequirements,
  buildPipRow,
  pipAuditValue,
  pipDateString,
  pipEventToManualOverride,
  pipOptionalInt,
  pipOptionalText,
  pipRequiredText,
} from "./pip-helpers";

interface CallExt extends CallRow {
  external_call_id: string;
  provider: string;
  contact_resolved_at?: string | null;
}
interface ApptExt extends AppointmentRow {
  acuity_appointment_id: string;
  client_name?: string | null;
  client_phone?: string | null;
  client_email?: string | null;
}
interface LeadExt extends LeadRow {
  source_id: string;
  provider: string;
  name?: string | null;
  phone?: string | null;
  email?: string | null;
}
interface BlockedExt extends BlockedTimeRow {
  provider: string;
  external_id: string;
}

export class MemoryStore implements Store {
  mode = "memory" as const;

  private settings: AppSettings = defaultSettings();
  private users = new Map<string, UserRow>();
  private contacts = new Map<string, ContactRow>();
  private calls = new Map<string, CallExt>(); // keyed by provider:external_call_id
  private harvestCalls = new Map<string, HarvestCallRow>(); // keyed by message_id (harvest_calls mirror)
  private harvestProgress = new Map<string, HarvestProgressRow>();
  private harvestConvs = new Map<string, HarvestConvRow & { visited: boolean; calls_found: number; messages_scanned: number }>();
  private opportunities = new Map<string, OpportunityRow>(); // keyed by provider:external_id
  private appointments = new Map<string, ApptExt>(); // keyed by acuity_appointment_id
  private attributions = new Map<string, AttributionRow>(); // keyed by appointment_id
  private leads = new Map<string, LeadExt>(); // keyed by sheet:source_id
  private availabilityRules: AvailabilityRule[] = [];
  private blocked = new Map<string, BlockedExt>();
  private teamGoals = new Map<string, TeamGoalRow>();
  private repGoals = new Map<string, RepGoalRowFull>();
  private monthlyGoals = new Map<string, MonthlyGoalRow>();
  private weeklyReportNotes = new Map<string, WeeklyReportNotesRow>();
  private connections = new Map<string, ConnectionRow>();
  private syncRuns: SyncRunRow[] = [];
  private watermarks = new Map<string, string>();
  private overrides: ManualOverrideRow[] = [];
  private dailyPriorities = new Map<string, DailyPrioritiesRow>();
  private leadAdjustments = new Map<string, LeadCountAdjustmentRow>(); // keyed work_date:sheet
  // Performance Management (PIP module): plain arrays — append-only histories.
  private pips: PipRow[] = [];
  private pipSnapshots: PipEvidenceSnapshotRow[] = [];
  private pipCheckins: PipCheckinRow[] = [];
  private pipTemplates: PipTemplateRow[] = [];
  private pipEvents: PipEventRow[] = [];
  // Commission Tracker (owner directive 2026-10-01, Phase A).
  private commissionWeekly = new Map<string, CommissionWeeklyRow>(); // keyed user_id:week_start
  private commissionCycles = new Map<string, CommissionCycleRow>(); // keyed by slug id
  private commissionAdjustments: CommissionAdjustmentRow[] = [];
  private seq = 0;

  private nextId(prefix: string): string {
    this.seq += 1;
    return `${prefix}_${this.seq}`;
  }

  private schemaDone = false;

  async ensureSchema(): Promise<void> {
    // Mirror the PG store's memoized DDL: the owner-set activation-date
    // backfill runs ONCE per store lifetime (Dan McKillop begins calling
    // 2026-09-28) so the Settings editor can later clear a date without it
    // snapping back on the next read. Commission seed profiles follow the
    // SAME fill-only-when-unset pattern (owner directive 2026-10-01).
    if (this.schemaDone) return;
    this.schemaDone = true;
    for (const u of this.users.values()) {
      if (u.call_start_date == null && DEFAULT_CALL_START_DATES[u.name]) {
        u.call_start_date = DEFAULT_CALL_START_DATES[u.name];
      }
      const seed = DEFAULT_COMMISSION_PROFILES[u.name];
      if (seed && u.commission_tier == null) {
        u.employment_type = seed.employment_type;
        u.commission_tier = seed.commission_tier;
        u.tier_effective_date = seed.tier_effective_date;
        u.tier_end_date = u.tier_end_date ?? null;
        u.commission_eligible = true;
      }
    }
  }

  async getSettings(): Promise<AppSettings> {
    // Normalize on read so settings saved before newer default fields existed
    // (e.g. sheets.<sheet>.mode) still see those defaults.
    return normalizeAppSettings(this.settings);
  }
  async saveSettings(patch: Partial<AppSettings>): Promise<AppSettings> {
    this.settings = {
      ...this.settings,
      ...patch,
      studio: { ...this.settings.studio, ...(patch.studio ?? {}) },
      sheets: { ...this.settings.sheets, ...(patch.sheets ?? {}) },
      acuity: { ...this.settings.acuity, ...(patch.acuity ?? {}) },
    };
    return JSON.parse(JSON.stringify(this.settings));
  }

  async upsertTeamGoal(row: TeamGoalRow): Promise<void> {
    this.teamGoals.set(row.week_start, { ...row });
  }
  async getTeamGoal(weekStart: string): Promise<TeamGoalRow | null> {
    return this.teamGoals.get(weekStart) ?? null;
  }
  async getTeamGoals(): Promise<TeamGoalRow[]> {
    return [...this.teamGoals.values()].sort((a, b) => (a.week_start < b.week_start ? -1 : 1));
  }
  async upsertRepGoals(rows: RepGoalRowFull[]): Promise<void> {
    for (const r of rows) this.repGoals.set(`${r.rep_id}:${r.week_start}`, { ...r });
  }
  async getRepGoals(weekStart: string): Promise<RepGoalRowFull[]> {
    return [...this.repGoals.values()].filter((r) => r.week_start === weekStart);
  }
  async deleteRepGoal(repId: string, weekStart: string): Promise<void> {
    this.repGoals.delete(`${repId}:${weekStart}`);
  }
  async upsertMonthlyGoal(row: MonthlyGoalRow): Promise<void> {
    this.monthlyGoals.set(row.month, { ...row });
  }
  async getMonthlyGoal(month: string): Promise<MonthlyGoalRow | null> {
    return this.monthlyGoals.get(month) ?? null;
  }
  async deleteMonthlyGoal(month: string): Promise<void> {
    this.monthlyGoals.delete(month);
  }
  async getWeeklyReportNotes(weekStart: string): Promise<WeeklyReportNotesRow | null> {
    return this.weeklyReportNotes.get(weekStart) ?? null;
  }
  async upsertWeeklyReportNotes(row: WeeklyReportNotesRow): Promise<void> {
    this.weeklyReportNotes.set(row.week_start, { ...row, notes: { ...row.notes } });
  }

  async upsertUsers(rows: UserRow[]): Promise<number> {
    for (const r of rows) {
      const existing = [...this.users.values()].find((u) => u.provider === r.provider && u.external_id === r.external_id);
      if (existing) this.users.set(existing.id, { ...existing, ...r, id: existing.id, call_start_date: r.call_start_date ?? existing.call_start_date ?? null });
      else {
        const key = this.nextId("u");
        // Commission profile fields always present on read (defaults = ineligible).
        const seeded: UserRow = {
          ...r,
          id: key,
          call_start_date: r.call_start_date ?? null,
          employment_type: r.employment_type ?? null,
          commission_tier: r.commission_tier ?? null,
          tier_effective_date: r.tier_effective_date ?? null,
          tier_end_date: r.tier_end_date ?? null,
          commission_eligible: r.commission_eligible ?? false,
        };
        this.users.set(key, seeded);
      }
    }
    return rows.length;
  }
  async setUserCallStartDate(repId: string, date: string | null): Promise<void> {
    const u = this.users.get(repId);
    if (u) this.users.set(repId, { ...u, call_start_date: date });
  }
  async getUsers(): Promise<UserRow[]> {
    await this.ensureSchema();
    // Active-roster users only — same semantics as the PG store's read.
    return [...this.users.values()].filter((u) => u.is_active);
  }
  async getAllUsers(): Promise<UserRow[]> {
    await this.ensureSchema();
    return [...this.users.values()];
  }

  async upsertContacts(rows: ContactRow[]): Promise<number> {
    for (const r of rows) {
      // Mirror of the PG store: raw values verbatim, canonical identity keys
      // derived at the boundary when not supplied, upsert-only (never delete).
      const patch: ContactRow = {
        ...r,
        phone_raw: r.phone_raw ?? r.phone,
        email_raw: r.email_raw ?? r.email,
        phone_normalized: r.phone_normalized ?? normalizeUSPhone(r.phone),
        email_normalized: r.email_normalized ?? normalizeEmail(r.email),
      };
      const existing = [...this.contacts.values()].find((c) => c.provider === r.provider && c.external_id === r.external_id);
      if (existing) {
        this.contacts.set(existing.id, {
          ...existing,
          ...patch,
          id: existing.id,
          name: patch.name ?? existing.name,
          assigned_rep_id: patch.assigned_rep_id ?? existing.assigned_rep_id,
          first_name: patch.first_name ?? existing.first_name ?? null,
          last_name: patch.last_name ?? existing.last_name ?? null,
          phone_raw: patch.phone_raw ?? existing.phone_raw ?? null,
          phone_normalized: patch.phone_normalized ?? existing.phone_normalized ?? null,
          email_raw: patch.email_raw ?? existing.email_raw ?? null,
          email_normalized: patch.email_normalized ?? existing.email_normalized ?? null,
          source_created_at: patch.source_created_at ?? existing.source_created_at ?? null,
          source_updated_at: patch.source_updated_at ?? existing.source_updated_at ?? null,
          last_synced_at: patch.last_synced_at ?? existing.last_synced_at ?? null,
        });
      } else {
        const key = this.nextId("c");
        this.contacts.set(key, { ...patch, id: key, created_at: r.created_at ?? new Date().toISOString() });
      }
    }
    return rows.length;
  }
  async getContacts(): Promise<ContactRow[]> {
    return [...this.contacts.values()];
  }
  async countContacts(provider: string): Promise<number> {
    return [...this.contacts.values()].filter((c) => c.provider === provider).length;
  }
  async getContactExternalIds(provider: string, only?: string[]): Promise<ContactExternalIdRow[]> {
    // Mirror of the PG store: two light columns, provider-scoped, optionally
    // narrowed to specific external ids.
    return [...this.contacts.values()]
      .filter((c) => c.provider === provider && (!only || only.includes(c.external_id)))
      .map((c) => ({ id: c.id, external_id: c.external_id }));
  }
  /** PERF: identity slice (mirror of PgStore.getContactIdentityRows). */
  async getContactIdentityRows(): Promise<ContactIdentityRow[]> {
    return [...this.contacts.values()].map((c) => ({
      id: c.id,
      phone: c.phone ?? null,
      email: c.email ?? null,
      assigned_rep_id: c.assigned_rep_id ?? null,
    }));
  }

  async upsertCalls(rows: CallExt[]): Promise<number> {
    for (const r of rows) {
      const key = `${r.provider}:${r.external_call_id}`;
      const existing = this.calls.get(key);
      // keep stable internal id across re-syncs
      this.calls.set(key, { ...r, id: existing?.id ?? this.nextId("call") });
    }
    return rows.length;
  }
  async getCallsBetween(startUtc: string, endUtc: string): Promise<CallRow[]> {
    return [...this.calls.values()]
      .filter((c) => c.started_at >= startUtc && c.started_at < endUtc)
      .map(({ provider: _p, ...rest }) => rest); // external_call_id now CARRIED (attribution engine reads it)
  }
  async getAllCallsSince(startUtc: string): Promise<CallRow[]> {
    return this.getCallsBetween(startUtc, "9999-12-31");
  }
  async getAuditCalls(startUtc: string, endUtc: string, repSpec: string | null, thresholdSeconds: number): Promise<AuditCallRow[]> {
    // Same semantics as the PG store (see its ownership comment): bucket specs
    // "non-roster" (owner KNOWN and outside the active roster — via rep_id
    // linkage OR resolved from the raw HL user id) / "unattributed" (no
    // determinable owner: rep NULL and the raw HL user id missing or
    // unresolved) / "unassigned" (legacy alias = union of both),
    // over_threshold per live threshold.
    await this.ensureSchema();
    const activeIds = new Set([...this.users.values()].filter((u) => u.is_active).map((u) => u.id));
    type CallAuditExt = CallExt & { conversation_id?: string | null; provider_rep_external_id?: string | null };
    const hlUserByKey = new Map([...this.users.values()].map((u) => [`${u.provider}:${u.external_id}`, u]));
    // Owner of one row: rep_id linkage first, else the raw provider user id.
    const ownerOf = (c: CallAuditExt): { id: string | null; name: string | null; isActive: boolean | null } => {
      if (c.rep_id !== null) {
        const u = this.users.get(c.rep_id);
        return { id: c.rep_id, name: u?.name ?? null, isActive: u ? u.is_active : false }; // dangling → treated non-roster
      }
      const prov = c.provider_rep_external_id ?? null;
      if (!prov) return { id: null, name: null, isActive: null };
      const pu = hlUserByKey.get(`${c.provider}:${prov}`) ?? null;
      return pu ? { id: pu.id, name: pu.name, isActive: pu.is_active } : { id: null, name: null, isActive: null };
    };
    const isNonRoster = (c: CallAuditExt): boolean => {
      const o = ownerOf(c);
      return o.id !== null && !activeIds.has(o.id);
    };
    const isUnattributed = (c: CallAuditExt): boolean => {
      if (c.rep_id !== null) return false;
      return ownerOf(c).id === null; // no prov, or prov resolves to no user row
    };
    const rows = [...this.calls.values()]
      .filter((c) => c.started_at >= startUtc && c.started_at < endUtc)
      .filter((c) => {
        if (!repSpec || repSpec === "all") return true;
        if (repSpec === "non-roster") return isNonRoster(c as CallAuditExt);
        if (repSpec === "unattributed") return isUnattributed(c as CallAuditExt);
        if (repSpec === "unassigned") return isNonRoster(c as CallAuditExt) || isUnattributed(c as CallAuditExt);
        return c.rep_id === repSpec;
      })
      .sort((a, b) => (a.started_at < b.started_at ? 1 : a.started_at > b.started_at ? -1 : a.external_call_id < b.external_call_id ? 1 : -1));
    return rows.map((c) => {
      const cx = c as CallAuditExt;
      const linked = c.rep_id ? this.users.get(c.rep_id) : undefined;
      const contact = c.contact_id ? this.contacts.get(c.contact_id) : undefined;
      const owner = ownerOf(cx);
      return {
        external_call_id: c.external_call_id,
        conversation_id: cx.conversation_id ?? null,
        rep_id: c.rep_id ?? null,
        // Raw linkage first; rows resolved from the raw HL user id show that
        // owner's name/state so Non Roster Calls are human-readable.
        rep_name: linked?.name ?? owner.name,
        rep_is_active: linked ? linked.is_active : owner.isActive,
        provider_rep_external_id: cx.provider_rep_external_id ?? null,
        contact_id: c.contact_id ?? null,
        contact_name: contact?.name ?? null,
        contact_external_id: contact?.external_id ?? null,
        contact_resolution_method: cx.contact_resolution_method ?? null,
        direction: (c as Partial<CallRow> & { direction?: string | null }).direction ?? null,
        call_status: (c as Partial<CallRow> & { call_status?: string | null }).call_status ?? null,
        started_at: c.started_at,
        duration_seconds: c.duration_seconds,
        over_threshold: c.duration_seconds > thresholdSeconds,
      };
    });
  }

  async upsertOpportunities(rows: OpportunityRow[]): Promise<number> {
    for (const r of rows) {
      const key = `${r.provider}:${r.external_id}`;
      const existing = this.opportunities.get(key);
      this.opportunities.set(key, { ...r, id: existing?.id ?? this.nextId("opp") });
    }
    return rows.length;
  }
  async getOpportunities(): Promise<OpportunityRow[]> {
    return [...this.opportunities.values()];
  }
  /** Opportunities on specific GHL pipelines (Alliance/Auction lead counts). */
  async getOpportunitiesByPipelines(pipelineIds: string[]): Promise<OpportunityRow[]> {
    const want = new Set(pipelineIds);
    return [...this.opportunities.values()].filter((o) => o.pipeline_id != null && want.has(o.pipeline_id));
  }

  /** Mirror of the PG store's demo-content replacement (see Store doc). */
  async deleteDemoHighLevelRows(): Promise<{ users: number; contacts: number; calls: number }> {
    const isDemoRow = (externalId: string | undefined) => typeof externalId === "string" && externalId.startsWith("demo-");
    let users = 0;
    let contacts = 0;
    let calls = 0;
    // attribution rows keep history: demo call links are nulled, rows stay
    const demoCallInternalIds = new Set(
      [...this.calls.values()].filter((c) => c.provider === "highlevel" && isDemoRow(c.external_call_id)).map((c) => c.id),
    );
    for (const [key, a] of this.attributions) {
      if (a.call_id && demoCallInternalIds.has(a.call_id)) this.attributions.set(key, { ...a, call_id: null });
    }
    for (const [key, c] of this.calls) {
      if (c.provider === "highlevel" && isDemoRow(c.external_call_id)) {
        this.calls.delete(key);
        calls += 1;
      }
    }
    const demoUserIds = new Set([...this.users.values()].filter((u) => u.provider === "highlevel" && isDemoRow(u.external_id)).map((u) => u.id));
    const demoContactIds = new Set([...this.contacts.values()].filter((c) => c.provider === "highlevel" && isDemoRow(c.external_id)).map((c) => c.id));
    for (const [key, a] of this.appointments) if (a.contact_id && demoContactIds.has(a.contact_id)) this.appointments.set(key, { ...a, contact_id: null });
    for (const [key, l] of this.leads) {
      const patch: Partial<LeadExt> = {};
      if (l.contact_id && demoContactIds.has(l.contact_id)) patch.contact_id = null;
      if (l.assigned_rep_id && demoUserIds.has(l.assigned_rep_id)) patch.assigned_rep_id = null;
      if (Object.keys(patch).length) this.leads.set(key, { ...l, ...patch });
    }
    for (const [key, o] of this.opportunities) {
      const patch: Partial<OpportunityRow> = {};
      if (o.contact_id && demoContactIds.has(o.contact_id)) patch.contact_id = null;
      if (o.rep_id && demoUserIds.has(o.rep_id)) patch.rep_id = null;
      if (Object.keys(patch).length) this.opportunities.set(key, { ...o, ...patch });
    }
    for (const c of this.contacts.values()) if (c.assigned_rep_id && demoUserIds.has(c.assigned_rep_id)) c.assigned_rep_id = null;
    for (const [key, c] of this.contacts) {
      if (c.provider === "highlevel" && isDemoRow(c.external_id)) {
        this.contacts.delete(key);
        contacts += 1;
      }
    }
    for (const key of [...this.repGoals.keys()]) if (demoUserIds.has(key.split(":")[0])) this.repGoals.delete(key);
    for (const [key, u] of this.users) {
      if (u.provider === "highlevel" && isDemoRow(u.external_id)) {
        this.users.delete(key);
        users += 1;
      }
    }
    return { users, contacts, calls };
  }

  async upsertAppointments(rows: ApptExt[]): Promise<number> {
    for (const r of rows) {
      const existing = this.appointments.get(r.acuity_appointment_id);
      // keep stable internal id across re-syncs; cancellations update in place.
      // BOOKING WIN (rev 12): win evidence is WRITE-ONCE — an existing
      // non-null win date / provenance / first-seen stamp is never overwritten
      // (mirror of the pg store's COALESCE upsert), so an appointment never
      // counts twice and its win date never moves.
      this.appointments.set(r.acuity_appointment_id, {
        ...r,
        booking_win_business_date: existing?.booking_win_business_date ?? r.booking_win_business_date ?? null,
        payment_business_date_source: existing?.payment_business_date_source ?? r.payment_business_date_source ?? null,
        first_seen_paid_at: existing?.first_seen_paid_at ?? r.first_seen_paid_at ?? null,
        // PENDING PAYMENT DISMISSAL (owner request 9/30): owner-controlled
        // state — a re-sync never overwrites or clears the dismissal.
        pending_dismissed_at: existing?.pending_dismissed_at ?? null,
        id: existing?.id ?? this.nextId("appt"),
      });
    }
    return rows.length;
  }
  private stripAppt(a: ApptExt): AppointmentRow {
    // acuity_appointment_id + client_name are PART of AppointmentRow (optional)
    // since the commission counted-booking snapshots need the provider id +
    // client label — only the phone/email extras stay stripped.
    const { client_phone: _p, client_email: _e, ...rest } = a;
    return rest;
  }
  async getAppointmentsCreatedBusinessDateBetween(start: string, end: string): Promise<AppointmentRow[]> {
    // S7c: created-based metrics bucket on the ET BUSINESS DATE column —
    // identical semantics to the pg store (the SQL path filters the column;
    // production rows all carry it after the S7c re-pull). The memory path
    // shares ONE derivation helper (createdBusinessDateOf) so the stores can
    // never diverge, including for legacy rows without the column.
    return [...this.appointments.values()]
      .filter((a) => {
        const d = createdBusinessDateOf(a);
        return d != null && d >= start && d <= end;
      })
      .map((a) => this.stripAppt(a));
  }
  async getAppointmentsByWinBusinessDateBetween(start: string, end: string): Promise<AppointmentRow[]> {
    // BOOKING WIN bucket (rev 12) — mirrors the pg SQL: wins by the persisted
    // win date (fallback derivation: created date for not-yet-derived paid
    // rows), UNION no-win-date rows by created date. The metrics layer applies
    // the win filters; unpaid rows here never count.
    return [...this.appointments.values()]
      .filter((a) => {
        const win = a.booking_win_business_date;
        if (win != null && win !== "") return win >= start && win <= end;
        const d = createdBusinessDateOf(a);
        return d != null && d >= start && d <= end;
      })
      .map((a) => this.stripAppt(a));
  }
  async getAppointmentsOverlapping(startUtc: string, endUtc: string): Promise<AppointmentRow[]> {
    // Availability path — mirrors pg.ts: carries the per-appointment duration,
    // calendar name (scope matching), acuity id AND the client contact fields
    // (the attribution engine's phone/email tiers read them from this selector).
    return [...this.appointments.values()]
      .filter((a) => a.appointment_datetime < endUtc && a.appointment_datetime >= startUtc)
      .map((a) => ({
        ...this.stripAppt(a),
        calendar_name: a.calendar_name ?? null,
        acuity_appointment_id: a.acuity_appointment_id,
        duration_minutes: a.duration_minutes ?? null,
        client_name: a.client_name ?? null,
        client_phone: a.client_phone ?? null,
        client_email: a.client_email ?? null,
      }));
  }
  async getAllAppointmentsSince(startUtc: string): Promise<AppointmentRow[]> {
    return [...this.appointments.values()]
      .filter((a) => a.appointment_datetime >= startUtc || a.created_at >= startUtc)
      .map((a) => this.stripAppt(a));
  }
  async getAppointmentsWithClientsSince(startUtc: string, opts?: { excludePendingDismissed?: boolean }): Promise<(AppointmentRow & {
    acuity_appointment_id: string | null;
    client_name: string | null;
    client_phone: string | null;
    client_email: string | null;
    calendar_name: string | null;
  })[]> {
    // Mirror of the pg store: excludePendingDismissed drops owner-dismissed
    // pending payments (pending_dismissed_at non-null) — pending list only.
    return [...this.appointments.values()]
      .filter((a) => (a.appointment_datetime >= startUtc || a.created_at >= startUtc) && (!opts?.excludePendingDismissed || a.pending_dismissed_at == null))
      .map((a) => ({
        ...this.stripAppt(a),
        acuity_appointment_id: a.acuity_appointment_id,
        client_name: a.client_name ?? null,
        client_phone: a.client_phone ?? null,
        client_email: a.client_email ?? null,
        calendar_name: (a as unknown as { calendar_name?: string | null }).calendar_name ?? null,
        pending_dismissed_at: a.pending_dismissed_at ?? null,
      }));
  }
  async dismissPendingPayment(appointmentId: string): Promise<void> {
    // KEEP-FIRST (idempotent): a re-dismiss never moves the original timestamp.
    // The appointment row itself is NEVER deleted (Acuity is the source of
    // truth; the sync would re-create it) — this only hides it from the
    // pending list. Unknown id: no-op (callers validate existence first).
    for (const [key, a] of this.appointments) {
      if (a.id === appointmentId) {
        this.appointments.set(key, { ...a, pending_dismissed_at: a.pending_dismissed_at ?? new Date().toISOString() });
        return;
      }
    }
  }

  async upsertAttributions(rows: AttributionRow[], opts?: { force?: boolean }): Promise<number> {
    // WRITER PROTECTION (owner directive 2026-09-27): the SAME degradation
    // guard as the PG store (one shared pure function — identical semantics;
    // the advisory lock is a PG-only concern, the memory store is
    // single-process). A write that would strip a large share of the
    // currently-attributed rows it touches is refused, never applied.
    if (!opts?.force) {
      const degrade = attributionDegradation([...this.attributions.values()], rows);
      if (degrade) {
        throw new Error(
          `attribution degradation guard: this write would strip ${degrade.stripped} of ${degrade.touched} currently-attributed bookings — refusing the rewrite (stale/buggy writer shape). Recovery: fix the writer, bump the writer version, or pass force.`,
        );
      }
    }
    for (const r of rows) {
      // mirror the PG store: never overwrite a manual override automatically
      const existing = this.attributions.get(r.appointment_id);
      if (existing?.manual_override) continue;
      this.attributions.set(r.appointment_id, { ...r });
    }
    return rows.length;
  }
  async getAttributions(): Promise<AttributionRow[]> {
    return [...this.attributions.values()];
  }
  async setManualAttribution(row: AttributionRow): Promise<void> {
    // manual assignment wins over the engine and survives re-syncs (engine
    // upserts skip rows with manual_override = true)
    this.attributions.set(row.appointment_id, { ...row, method: "manual", manual_override: true });
  }
  async deleteAttribution(appointmentId: string): Promise<void> {
    // manual UNASSIGN: mirror the PG store — delete the derived row; the next
    // attribution tick recomputes the appointment from raw rows
    this.attributions.delete(appointmentId);
  }

  async deleteLeadsForSheet(sourceSheet: string): Promise<void> {
    for (const [key, lead] of this.leads) {
      if (lead.provider === "google_sheets" && lead.source_sheet === sourceSheet) this.leads.delete(key);
    }
  }
  async getLeadsByProvider(provider: string): Promise<(LeadRow & { source_id: string; provider: string; name: string | null; phone: string | null; email: string | null })[]> {
    return [...this.leads.values()]
      .filter((l) => l.provider === provider)
      .map((l) => ({
        id: l.id,
        source_id: l.source_id,
        provider: l.provider,
        lead_type: l.lead_type,
        source_date: l.source_date,
        work_date: l.work_date,
        name: l.name ?? null,
        phone: l.phone ?? null,
        email: l.email ?? null,
        contact_id: l.contact_id,
        assigned_rep_id: l.assigned_rep_id,
        source_sheet: l.source_sheet,
      }));
  }
  async deleteLeadsBySourceIds(provider: string, sourceIds: string[]): Promise<number> {
    const set = new Set(sourceIds);
    let n = 0;
    for (const [key, lead] of this.leads) {
      if (lead.provider === provider && set.has(lead.source_id)) {
        this.leads.delete(key);
        n++;
      }
    }
    return n;
  }
  async upsertLeads(rows: LeadExt[]): Promise<number> {
    for (const r of rows) {
      const key = `${r.provider}:${r.source_id}`;
      const existing = this.leads.get(key);
      this.leads.set(key, { ...r, id: existing?.id ?? this.nextId("lead") });
    }
    return rows.length;
  }
  async countLeads(provider: string): Promise<number> {
    let n = 0;
    for (const lead of this.leads.values()) if (lead.provider === provider) n++;
    return n;
  }
  async getLeadsByWorkDates(dates: string[]): Promise<LeadRow[]> {
    const set = new Set(dates);
    return [...this.leads.values()]
      .filter((l) => set.has(l.work_date))
      .map(({ source_id: _s, provider: _p, name: _n, phone: _p2, email: _e, ...rest }) => rest);
  }
  async getLeadsBySourceDates(dates: string[]): Promise<LeadRow[]> {
    const set = new Set(dates);
    return [...this.leads.values()]
      .filter((l) => set.has(l.source_date))
      .map(({ source_id: _s, provider: _p, name: _n, phone: _p2, email: _e, ...rest }) => rest);
  }
  async updateLeadWorkDate(id: string, workDate: string): Promise<void> {
    for (const [key, lead] of this.leads) {
      if (lead.id === id) {
        this.leads.set(key, { ...lead, work_date: workDate });
        return;
      }
    }
    throw new Error(`Lead ${id} not found`);
  }

  async upsertLeadCountAdjustment(row: Omit<LeadCountAdjustmentRow, "updated_at">): Promise<void> {
    if (!row.delta) {
      // corrected back to the observed count → the adjustment disappears
      this.leadAdjustments.delete(`${row.work_date}:${row.sheet}`);
      return;
    }
    this.leadAdjustments.set(`${row.work_date}:${row.sheet}`, { ...row, updated_at: new Date().toISOString() });
  }
  async getLeadCountAdjustments(dates: string[]): Promise<LeadCountAdjustmentRow[]> {
    const set = new Set(dates);
    return [...this.leadAdjustments.values()].filter((a) => set.has(a.work_date));
  }

  /** REPLACE semantics (mirror == settings.studio.hours exactly); sorted read. */
  async upsertAvailabilityRules(rows: AvailabilityRule[]): Promise<void> {
    this.availabilityRules = rows.map((r) => ({ ...r }));
  }
  async getAvailabilityRules(): Promise<AvailabilityRule[]> {
    return this.availabilityRules
      .map((r) => ({ ...r }))
      .sort((a, b) => a.weekday - b.weekday || a.open_time.localeCompare(b.open_time));
  }
  async upsertBlockedTimes(rows: BlockedExt[]): Promise<number> {
    for (const r of rows) this.blocked.set(`${r.provider}:${r.external_id}`, { ...r });
    return rows.length;
  }
  async deleteDemoAcuityRows(): Promise<{ appointments: number; blocked: number }> {
    // Mirror pg.ts: drop the demo generator's Acuity appointments (ids
    // prefixed "demo-") + demo blocked rows (provider acuity); manual blocks
    // and recurring blocks stay. Idempotent.
    let appointments = 0;
    for (const [key, a] of this.appointments) {
      if (a.acuity_appointment_id.startsWith("demo-")) {
        this.appointments.delete(key);
        appointments += 1;
      }
    }
    let blocked = 0;
    for (const [key, b] of this.blocked) {
      if (b.provider === "acuity" && b.external_id.startsWith("demo-")) {
        this.blocked.delete(key);
        blocked += 1;
      }
    }
    return { appointments, blocked };
  }
  async getBlockedTimesBetween(startUtc: string, endUtc: string): Promise<BlockedTimeRow[]> {
    return [...this.blocked.values()]
      .filter((b) => b.end_at > startUtc && b.start_at < endUtc)
      .map(({ provider: _p, external_id: _e, ...rest }) => rest);
  }
  async insertBlockedTime(row: { start_at: string; end_at: string; reason: string | null }): Promise<BlockedTimeRow> {
    const id = this.nextId("block");
    this.blocked.set(`manual:${id}`, {
      provider: "manual",
      external_id: id,
      id,
      start_at: row.start_at,
      end_at: row.end_at,
      reason: row.reason,
    });
    return { id, start_at: row.start_at, end_at: row.end_at, reason: row.reason };
  }
  async deleteBlockedTime(id: string): Promise<void> {
    for (const [key, block] of this.blocked) {
      if (block.id === id) {
        this.blocked.delete(key);
        return;
      }
    }
  }

  async upsertDailyPriorities(row: DailyPrioritiesRow): Promise<void> {
    this.dailyPriorities.set(row.date, { ...row });
  }
  async getDailyPriorities(date: string): Promise<DailyPrioritiesRow | null> {
    return this.dailyPriorities.get(date) ?? null;
  }

  async upsertConnection(row: ConnectionRow): Promise<void> {
    this.connections.set(row.provider, { ...row });
  }
  async getConnections(): Promise<ConnectionRow[]> {
    return [...this.connections.values()];
  }

  async insertSyncRun(provider: string): Promise<string> {
    const id = this.nextId("sync");
    this.syncRuns.push({ id, provider, status: "running", started_at: new Date().toISOString(), finished_at: null, records_upserted: 0, error: null });
    return id;
  }
  async finishSyncRun(id: string, status: string, recordsUpserted: number, error: string | null): Promise<void> {
    const run = this.syncRuns.find((r) => r.id === id);
    if (run) {
      run.status = status;
      run.records_upserted = recordsUpserted;
      run.error = error;
      run.finished_at = new Date().toISOString();
    }
  }
  async getSyncRuns(limit: number): Promise<SyncRunRow[]> {
    return this.syncRuns.slice(-limit).reverse();
  }
  async getRunningSyncRuns(): Promise<SyncRunRow[]> {
    return this.syncRuns.filter((r) => r.status === "running" && r.finished_at === null);
  }
  async getRunningSyncRun(provider: string): Promise<SyncRunRow | null> {
    const running = this.syncRuns.filter((r) => r.provider === provider && r.status === "running" && r.finished_at === null);
    const run = running.length ? running[running.length - 1] : null;
    if (!run) return null;
    // FRESHNESS BOUND: a zombie (or unparsable) started_at is NOT a live run.
    const startedMs = parseSyncStartedMs(run.started_at);
    if (!Number.isFinite(startedMs)) return null;
    if (Date.now() - startedMs > STALE_RUN_REAP_MINUTES * 60_000) return null;
    return run;
  }
  async getSyncWatermark(provider: string): Promise<string | null> {
    return this.watermarks.get(provider) ?? null;
  }
  async setSyncWatermark(provider: string, watermarkIso: string): Promise<void> {
    this.watermarks.set(provider, watermarkIso);
  }
  private checkpoints = new Map<string, string>();
  async getSyncCheckpoint(key: string): Promise<string | null> {
    return this.checkpoints.get(key) ?? null;
  }
  async setSyncCheckpoint(key: string, value: string): Promise<void> {
    this.checkpoints.set(key, value);
  }

  async insertManualOverride(row: Omit<ManualOverrideRow, "id" | "changed_at">): Promise<void> {
    this.overrides.push({ ...row, id: this.nextId("ovr"), changed_at: new Date().toISOString() });
  }
  async getManualOverrides(limit: number): Promise<ManualOverrideRow[]> {
    return this.overrides.slice(-limit).reverse();
  }

  // ---- call harvest (resumable; mirrors PgStore semantics) ----
  async getHarvestProgress(id = "highlevel-calls"): Promise<HarvestProgressRow | null> {
    const p = this.harvestProgress.get(id);
    return p ? { ...p } : null;
  }
  async saveHarvestProgress(p: HarvestProgressRow): Promise<void> {
    this.harvestProgress.set(p.id, { ...p });
  }
  async upsertHarvestConversations(rows: HarvestConvRow[]): Promise<number> {
    for (const r of rows) {
      const prev = this.harvestConvs.get(r.conv_id);
      if (prev) {
        this.harvestConvs.set(r.conv_id, {
          ...r,
          message_types: [...new Set([...prev.message_types, ...r.message_types])],
          last_message_type: r.last_message_type ?? prev.last_message_type,
          contact_id: r.contact_id ?? prev.contact_id,
          assigned_to: r.assigned_to ?? prev.assigned_to,
          visited: prev.visited,
          calls_found: prev.calls_found,
          messages_scanned: prev.messages_scanned,
        });
      } else {
        this.harvestConvs.set(r.conv_id, { ...r, visited: false, calls_found: 0, messages_scanned: 0 });
      }
    }
    return rows.length;
  }
  async getUnvisitedInWindow(windowStartMs: number, limit: number, callFlaggedFirst: boolean): Promise<HarvestConvRow[]> {
    const rows = [...this.harvestConvs.values()]
      .filter((c) => !c.visited && c.last_message_date >= windowStartMs);
    const flagged = (c: (typeof rows)[number]) => c.message_types.includes(1) || c.last_message_type === "TYPE_CALL" ? 1 : 0;
    rows.sort((a, b) => (callFlaggedFirst ? flagged(b) - flagged(a) : 0) || b.last_message_date - a.last_message_date);
    return rows.slice(0, limit).map(({ visited, calls_found, messages_scanned, ...r }) => r);
  }
  async getHarvestConversationsByIds(convIds: string[]): Promise<HarvestConvRow[]> {
    if (!convIds.length) return [];
    const set = new Set(convIds);
    return [...this.harvestConvs.values()]
      .filter((c) => set.has(c.conv_id))
      .map(({ visited, calls_found, messages_scanned, ...r }) => r);
  }
  async upsertHarvestCalls(rows: HarvestCallRow[]): Promise<number> {
    for (const r of rows) this.harvestCalls.set(r.message_id, { ...r });
    return rows.length;
  }
  async getHarvestCallsByMessageIds(messageIds: string[]): Promise<HarvestCallRow[]> {
    if (!messageIds.length) return [];
    const set = new Set(messageIds);
    return [...this.harvestCalls.values()].filter((r) => set.has(r.message_id)).map((r) => ({ ...r }));
  }
  async getHarvestCallsSince(startUtc: string): Promise<HarvestCallRow[]> {
    const startMs = Date.parse(startUtc);
    return [...this.harvestCalls.values()]
      .filter((r) => Number.isFinite(Date.parse(r.started_at)) && Date.parse(r.started_at) >= startMs)
      .map((r) => ({ ...r }));
  }
  async applyCallContactBackfill(rows: CallContactBackfillUpdate[]): Promise<void> {
    for (const r of rows) {
      // FILL-NULL-ONLY (owner rule, mirrors pg.ts): an existing non-null
      // contact_id is NEVER overwritten — direct source data always wins.
      const call = [...this.calls.values()].find((c) => c.id === r.call_id);
      if (!call) continue;
      const key = `${call.provider}:${call.external_call_id}`;
      if (call.contact_id == null) {
        this.calls.set(key, {
          ...call,
          contact_id: r.contact_id,
          contact_resolution_method: r.resolution_method,
          contact_resolved_at: r.contact_resolved_at,
        });
      }
    }
  }
  async markHarvestVisited(convIds: string[], callsFoundByConv: Record<string, number>, messagesScannedByConv?: Record<string, number>): Promise<void> {
    for (const id of convIds) {
      const prev = this.harvestConvs.get(id);
      if (prev) {
        this.harvestConvs.set(id, {
          ...prev,
          visited: true,
          calls_found: callsFoundByConv[id] ?? 0,
          messages_scanned: prev.messages_scanned + (messagesScannedByConv?.[id] ?? 0),
        });
      }
    }
  }
  async getHarvestCoverageSummary(windowStartMs: number): Promise<{ total: number; visited: number; callFlagged: number; byDay: { day: string; total: number; visited: number }[] }> {
    const inWindow = [...this.harvestConvs.values()].filter((c) => c.last_message_date >= windowStartMs);
    const etDay = (ms: number): string => new Intl.DateTimeFormat("en-CA", { timeZone: "America/New_York" }).format(new Date(ms));
    const byDay = new Map<string, { total: number; visited: number }>();
    for (const c of inWindow) {
      const day = etDay(c.last_message_date);
      const cur = byDay.get(day) ?? { total: 0, visited: 0 };
      cur.total += 1;
      if (c.visited) cur.visited += 1;
      byDay.set(day, cur);
    }
    return {
      total: inWindow.length,
      visited: inWindow.filter((c) => c.visited).length,
      callFlagged: inWindow.filter((c) => c.message_types.includes(1) || c.last_message_type === "TYPE_CALL").length,
      byDay: [...byDay.entries()].sort((a, b) => (a[0] < b[0] ? 1 : -1)).map(([day, v]) => ({ day, ...v })),
    };
  }

  // ---- Performance Management (PIP module — mirrors PgStore semantics exactly) ----
  private recordPipEvent(
    event: Omit<PipEventRow, "id" | "created_at">,
  ): void {
    this.pipEvents.push({ ...event, id: this.nextId("pipevt"), created_at: new Date().toISOString() });
    // Compact mirror into the existing audit trail (Settings → Audit page).
    this.overrides.push({
      ...pipEventToManualOverride(event.event_type, {
        entityId: event.pip_id ?? event.template_id ?? "",
        field: event.field,
        previousValue: event.previous_value,
        newValue: event.new_value,
        actor: event.actor,
      }),
      id: this.nextId("ovr"),
      changed_at: new Date().toISOString(),
    });
  }

  async createPip(input: PipCreateInput): Promise<PipRow> {
    const nowIso = new Date().toISOString();
    const row = buildPipRow(input, this.nextId("pip"), nowIso);
    this.pips.push(row);
    this.recordPipEvent({
      pip_id: row.id,
      template_id: null,
      event_type: "pip_created",
      actor: row.created_by,
      field: "status",
      previous_value: null,
      new_value: "draft",
      details: { title: row.title, rep_id: row.rep_id },
    });
    return { ...row };
  }

  async updatePipDraft(id: string, patch: PipDraftPatch): Promise<PipRow> {
    const row = this.pips.find((p) => p.id === id);
    if (!row) throw new Error(`PIP not found: ${id}`);
    const { next, changed, observationsBefore } = applyPipDraftPatch(row, patch);
    if (changed.length === 0) return { ...row };
    next.updated_at = new Date().toISOString();
    Object.assign(row, next);
    const actor = patch.actor ? String(patch.actor).trim() || null : null;
    this.recordPipEvent({
      pip_id: row.id,
      template_id: null,
      event_type: "pip_edited",
      actor,
      field: "draft",
      previous_value: null,
      new_value: changed.join(", "),
      details: { changed },
    });
    if (observationsBefore !== undefined && changed.includes("manager_observations")) {
      this.recordPipEvent({
        pip_id: row.id,
        template_id: null,
        event_type: "pip_observation_changed",
        actor,
        field: "manager_observations",
        previous_value: pipAuditValue(observationsBefore),
        new_value: pipAuditValue(row.manager_observations),
        details: null,
      });
    }
    return { ...row };
  }

  async getPip(id: string): Promise<PipRow | null> {
    const row = this.pips.find((p) => p.id === id);
    return row ? { ...row } : null;
  }

  async listPips(status?: PipStatus | null): Promise<PipRow[]> {
    return this.pips
      .filter((p) => !status || p.status === status)
      .sort((a, b) => (a.created_at < b.created_at ? 1 : -1))
      .map((p) => ({ ...p }));
  }

  async issuePip(id: string, opts: { issuedBy: string; snapshotExtras?: Record<string, unknown> }): Promise<PipRow> {
    const row = this.pips.find((p) => p.id === id);
    if (!row) throw new Error(`PIP not found: ${id}`);
    assertIssueRequirements(row);
    // Freeze the evidence FIRST (the exact document being issued), then flip.
    // PHASE 2 shape: the frozen document carries the pip row AS IT STOOD plus
    // the pre-computed evidence extras — never recomputed, never rewritten.
    const capturedAt = new Date().toISOString();
    const doc = JSON.parse(
      JSON.stringify({
        snapshot_schema: 2,
        captured_at: capturedAt,
        captured_by: opts.issuedBy || null,
        pip: row,
        ...(opts.snapshotExtras ?? {}),
      }),
    ) as Record<string, unknown>;
    this.pipSnapshots.push({
      id: this.nextId("pipsnap"),
      pip_id: row.id,
      version: 1,
      snapshot: doc,
      created_by: opts.issuedBy || null,
      created_at: capturedAt,
    });
    row.status = "issued";
    row.issued_at = new Date().toISOString();
    row.issued_by = opts.issuedBy || null;
    row.updated_at = row.issued_at;
    this.recordPipEvent({
      pip_id: row.id,
      template_id: null,
      event_type: "pip_issued",
      actor: opts.issuedBy || null,
      field: "status",
      previous_value: "draft",
      new_value: "issued",
      details: { version: 1, snapshot: "pip_evidence_snapshots v1 written" },
    });
    return { ...row };
  }

  async completePip(id: string, opts: { conclusionCategory: string; conclusionNotes: string; actor: string }): Promise<PipRow> {
    const row = this.pips.find((p) => p.id === id);
    if (!row) throw new Error(`PIP not found: ${id}`);
    const { category, notes } = assertCompleteRequirements(row, opts.conclusionCategory, opts.conclusionNotes);
    row.status = "completed";
    row.conclusion_category = category;
    row.conclusion_notes = notes;
    row.completed_at = new Date().toISOString();
    row.manager_acked_at = row.completed_at;
    row.manager_acked_by = opts.actor || null;
    row.updated_at = row.completed_at;
    this.recordPipEvent({
      pip_id: row.id,
      template_id: null,
      event_type: "pip_completed",
      actor: opts.actor || null,
      field: "status",
      previous_value: "issued",
      new_value: "completed",
      details: { conclusion_category: category },
    });
    return { ...row };
  }

  async cancelPip(id: string, opts: { cancelledBy: string; reason: string }): Promise<PipRow> {
    const row = this.pips.find((p) => p.id === id);
    if (!row) throw new Error(`PIP not found: ${id}`);
    const reason = assertCancelRequirements(row, opts.reason);
    row.status = "cancelled";
    row.cancellation_reason = reason;
    row.cancelled_at = new Date().toISOString();
    row.cancelled_by = opts.cancelledBy || null;
    row.updated_at = row.cancelled_at;
    this.recordPipEvent({
      pip_id: row.id,
      template_id: null,
      event_type: "pip_cancelled",
      actor: opts.cancelledBy || null,
      field: "status",
      previous_value: "issued",
      new_value: "cancelled",
      details: { reason: pipAuditValue(reason) },
    });
    return { ...row };
  }

  async addPipCheckin(row: Omit<PipCheckinRow, "id" | "created_at">): Promise<PipCheckinRow> {
    const pip = this.pips.find((p) => p.id === row.pip_id);
    if (!pip) throw new Error(`PIP not found: ${row.pip_id}`);
    assertCheckinAllowed(pip);
    const checkinDate = pipDateString(row.checkin_date, "checkin_date");
    const full: PipCheckinRow = {
      ...row,
      pip_id: row.pip_id,
      checkin_date: checkinDate ?? new Date().toISOString().slice(0, 10),
      manager_name: row.manager_name ?? null,
      employee_name: row.employee_name ?? null,
      current_performance: row.current_performance ?? null,
      topics_discussed: row.topics_discussed ?? null,
      coaching_provided: row.coaching_provided ?? null,
      employee_comments: row.employee_comments ?? null,
      manager_notes: row.manager_notes ?? null,
      next_actions: row.next_actions ?? null,
      next_checkin_date: pipDateString(row.next_checkin_date, "next_checkin_date"),
      id: this.nextId("pipchk"),
      created_at: new Date().toISOString(),
    };
    this.pipCheckins.push(full);
    this.recordPipEvent({
      pip_id: row.pip_id,
      template_id: null,
      event_type: "pip_checkin_added",
      actor: row.manager_name || null,
      field: "checkin",
      previous_value: null,
      new_value: full.checkin_date,
      details: null,
    });
    return { ...full };
  }

  async getPipCheckins(pipId: string): Promise<PipCheckinRow[]> {
    return this.pipCheckins
      .filter((c) => c.pip_id === pipId)
      .sort((a, b) => (a.created_at > b.created_at ? 1 : -1))
      .map((c) => ({ ...c }));
  }

  async getPipEvidenceSnapshots(pipId: string): Promise<PipEvidenceSnapshotRow[]> {
    return this.pipSnapshots
      .filter((s) => s.pip_id === pipId)
      .sort((a, b) => a.version - b.version)
      .map((s) => ({ ...s, snapshot: { ...s.snapshot } }));
  }

  async createPipTemplate(input: PipTemplateCreateInput): Promise<PipTemplateRow> {
    const name = pipRequiredText(input.name, "template name", 200);
    const nowIso = new Date().toISOString();
    const row: PipTemplateRow = {
      id: this.nextId("piptpl"),
      name,
      category: pipOptionalText(input.category ?? null, 120),
      default_goal_text: pipOptionalText(input.default_goal_text ?? null),
      default_action_plan: normalizePipActionList(input.default_action_plan ?? []),
      default_personal: normalizePipActionList(input.default_personal ?? []),
      default_professional: normalizePipActionList(input.default_professional ?? []),
      default_checkin_cadence_days: pipOptionalInt(input.default_checkin_cadence_days ?? null, "default_checkin_cadence_days"),
      default_duration_weeks: pipOptionalInt(input.default_duration_weeks ?? null, "default_duration_weeks"),
      version: 1,
      created_by: input.created_by ? String(input.created_by).trim() || null : null,
      created_at: nowIso,
      updated_at: nowIso,
    };
    this.pipTemplates.push(row);
    this.recordPipEvent({
      pip_id: null,
      template_id: row.id,
      event_type: "pip_template_created",
      actor: row.created_by,
      field: "name",
      previous_value: null,
      new_value: row.name,
      details: null,
    });
    return { ...row };
  }

  async updatePipTemplate(id: string, patch: PipTemplatePatch): Promise<PipTemplateRow> {
    const row = this.pipTemplates.find((t) => t.id === id);
    if (!row) throw new Error(`PIP template not found: ${id}`);
    if (patch.name !== undefined) row.name = pipRequiredText(patch.name, "template name", 200);
    if (patch.category !== undefined) row.category = pipOptionalText(patch.category, 120);
    if (patch.default_goal_text !== undefined) row.default_goal_text = pipOptionalText(patch.default_goal_text);
    if (patch.default_action_plan !== undefined) row.default_action_plan = normalizePipActionList(patch.default_action_plan);
    if (patch.default_personal !== undefined) row.default_personal = normalizePipActionList(patch.default_personal);
    if (patch.default_professional !== undefined) row.default_professional = normalizePipActionList(patch.default_professional);
    if (patch.default_checkin_cadence_days !== undefined)
      row.default_checkin_cadence_days = pipOptionalInt(patch.default_checkin_cadence_days, "default_checkin_cadence_days");
    if (patch.default_duration_weeks !== undefined)
      row.default_duration_weeks = pipOptionalInt(patch.default_duration_weeks, "default_duration_weeks");
    // EVERY edit is a new version — issued PIPs keep the version they were
    // issued with (frozen in their snapshots; the template moves on).
    row.version += 1;
    row.updated_at = new Date().toISOString();
    this.recordPipEvent({
      pip_id: null,
      template_id: row.id,
      event_type: "pip_template_updated",
      actor: patch.actor || null,
      field: "template",
      previous_value: null,
      new_value: row.name,
      details: { version: row.version },
    });
    return { ...row };
  }

  async deletePipTemplate(id: string): Promise<void> {
    const idx = this.pipTemplates.findIndex((t) => t.id === id);
    if (idx === -1) return;
    const [removed] = this.pipTemplates.splice(idx, 1);
    this.recordPipEvent({
      pip_id: null,
      template_id: id,
      event_type: "pip_template_deleted",
      actor: null,
      field: "name",
      previous_value: removed.name,
      new_value: null,
      details: null,
    });
  }

  async getPipTemplate(id: string): Promise<PipTemplateRow | null> {
    const row = this.pipTemplates.find((t) => t.id === id);
    return row ? { ...row } : null;
  }

  async listPipTemplates(): Promise<PipTemplateRow[]> {
    return this.pipTemplates.map((t) => ({ ...t }));
  }

  async getPipTemplateUsage(): Promise<Map<string, number>> {
    const out = new Map<string, number>();
    for (const p of this.pips) {
      if (!p.template_id || p.status === "draft") continue;
      out.set(p.template_id, (out.get(p.template_id) ?? 0) + 1);
    }
    return out;
  }

  async insertPipEvent(row: Omit<PipEventRow, "id" | "created_at">): Promise<void> {
    this.recordPipEvent(row);
  }

  async getPipEvents(opts?: { pipId?: string; limit?: number }): Promise<PipEventRow[]> {
    const rows = opts?.pipId ? this.pipEvents.filter((e) => e.pip_id === opts.pipId) : [...this.pipEvents];
    return rows
      .sort((a, b) => (a.created_at < b.created_at ? 1 : -1))
      .slice(0, opts?.limit ?? 200)
      .map((e) => ({ ...e, details: e.details ? { ...e.details } : null }));
  }

  // ---- Commission Tracker (owner directive 2026-10-01, Phase A) ----

  async setUserCommissionProfile(repId: string, profile: CommissionProfileInput | null): Promise<void> {
    const u = this.users.get(repId);
    if (!u) return;
    if (profile === null) {
      this.users.set(repId, { ...u, employment_type: null, commission_tier: null, tier_effective_date: null, tier_end_date: null, commission_eligible: false });
      return;
    }
    this.users.set(repId, { ...u, ...profile });
  }

  /**
   * Phase C SUBMITTED-CYCLE LOCK (spec §O/§19): a record whose assignment is
   * 'previously_submitted' — or whose cycle row is status 'submitted' — can
   * NEVER be rewritten. The attempted rewrite no-ops and lands in the audit
   * trail (who=system guard / what=old→new / when) so the attempt is visible
   * forever. Unlocked records keep the Phase-A idempotent replace behavior.
   */
  async upsertCommissionWeeklyRecord(row: CommissionWeeklyRow): Promise<CommissionUpsertResult> {
    const key = `${row.user_id}:${row.week_start}`;
    const existing = this.commissionWeekly.get(key);
    if (existing) {
      const cycle = existing.cycle_id ? this.commissionCycles.get(existing.cycle_id) : undefined;
      const locked = existing.assignment === "previously_submitted" || cycle?.status === "submitted";
      if (locked) {
        await this.insertCommissionAdjustment({
          cycle_id: existing.cycle_id,
          user_id: row.user_id,
          target: "weekly_record",
          target_id: key,
          field: "rewrite_blocked",
          old_value: `bookings ${existing.qualifying_bookings} · total ${existing.total.toFixed(2)} · calc v${existing.calc_version}`,
          new_value: `attempted bookings ${row.qualifying_bookings} · total ${row.total.toFixed(2)} · calc v${row.calc_version}`,
          reason: `Blocked by submitted-cycle lock: record belongs to ${existing.assignment === "previously_submitted" ? "a previously submitted" : `submitted cycle ${existing.cycle_id}`} — stored payroll is frozen (spec §19).`,
          changed_by: "system:write-guard",
        });
        return { written: false, blocked: true };
      }
    }
    // Idempotent by (user_id, week_start) — mirrors the pg UNIQUE key.
    this.commissionWeekly.set(key, { ...row, counted_bookings: [...(row.counted_bookings ?? [])], hole_audit: [...(row.hole_audit ?? [])] });
    return { written: true, blocked: false };
  }
  /** §O/§20: move ONLY the audited money fields (manual_adjustment, total) by a dollars delta. */
  async applyCommissionWeeklyCorrection(userId: string, weekStart: string, deltaDollars: number): Promise<void> {
    const key = `${userId}:${weekStart}`;
    const existing = this.commissionWeekly.get(key);
    if (!existing) throw new Error(`No stored weekly record for ${key} — corrections target stored records only.`);
    const cents = Math.round((existing.manual_adjustment + deltaDollars) * 100);
    const totalCents = Math.round((existing.total + deltaDollars) * 100);
    this.commissionWeekly.set(key, { ...existing, manual_adjustment: cents / 100, total: totalCents / 100 });
  }
  /** §S membership update: cycle_id/assignment only — money columns untouched. */
  async setCommissionRecordAssignment(userId: string, weekStart: string, patch: { cycleId: string | null; assignment: CommissionAssignment }): Promise<void> {
    const key = `${userId}:${weekStart}`;
    const existing = this.commissionWeekly.get(key);
    if (!existing) throw new Error(`No stored weekly record for ${key} — membership updates target stored records only.`);
    this.commissionWeekly.set(key, { ...existing, cycle_id: patch.cycleId, assignment: patch.assignment });
  }

  async getCommissionWeeklyRecords(filter?: { userId?: string; weekStart?: string; cycleId?: string; assignment?: CommissionAssignment }): Promise<CommissionWeeklyRow[]> {
    let rows = [...this.commissionWeekly.values()];
    if (filter?.userId) rows = rows.filter((r) => r.user_id === filter.userId);
    if (filter?.weekStart) rows = rows.filter((r) => r.week_start === filter.weekStart);
    if (filter?.cycleId) rows = rows.filter((r) => r.cycle_id === filter.cycleId);
    if (filter?.assignment) rows = rows.filter((r) => r.assignment === filter.assignment);
    return rows
      .sort((a, b) => (a.week_start < b.week_start ? 1 : -1))
      .map((r) => ({ ...r, counted_bookings: [...r.counted_bookings], hole_audit: [...(r.hole_audit ?? [])] }));
  }

  async upsertCommissionCycle(cycle: CommissionCycleRow): Promise<void> {
    this.commissionCycles.set(cycle.id, { ...cycle });
  }

  async getCommissionCycle(cycleId: string): Promise<CommissionCycleRow | null> {
    const row = this.commissionCycles.get(cycleId);
    return row ? { ...row } : null;
  }

  async getCommissionCycles(): Promise<CommissionCycleRow[]> {
    return [...this.commissionCycles.values()]
      .sort((a, b) => (a.start_date < b.start_date ? 1 : -1))
      .map((c) => ({ ...c }));
  }

  async insertCommissionAdjustment(row: CommissionAdjustmentInput): Promise<CommissionAdjustmentRow> {
    // §O/§29: the reason is REQUIRED — enforced HERE (both stores).
    if (typeof row.reason !== "string" || row.reason.trim().length === 0) {
      throw new Error("A correction reason is required (who/what/old/new/reason/when audit).");
    }
    const full: CommissionAdjustmentRow = { ...row, reason: row.reason.trim(), id: this.nextId("cadj"), changed_at: new Date().toISOString() };
    this.commissionAdjustments.push(full);
    return { ...full };
  }

  async getCommissionAdjustments(filter?: { cycleId?: string; userId?: string; targetId?: string }): Promise<CommissionAdjustmentRow[]> {
    let rows = [...this.commissionAdjustments];
    if (filter?.cycleId) rows = rows.filter((r) => r.cycle_id === filter.cycleId);
    if (filter?.userId) rows = rows.filter((r) => r.user_id === filter.userId);
    if (filter?.targetId) rows = rows.filter((r) => r.target_id === filter.targetId);
    return rows.sort((a, b) => (a.changed_at < b.changed_at ? 1 : -1)).map((r) => ({ ...r }));
  }
}
