/**
 * In-memory Store — used when Postgres is unreachable (e.g. DATABASE_URL
 * incomplete). Mirrors the Postgres store's duplicate-safe upsert semantics:
 * rows are keyed by provider external IDs, so re-running syncs REPLACES rows
 * instead of duplicating. Demo data is generated by the same generator that
 * feeds the Postgres store.
 */
import {
  type AppointmentRow,
  type AttributionRow,
  type AvailabilityRule,
  type BlockedTimeRow,
  type CallRow,
  type LeadRow,
} from "../metrics/compute";
import { normalizeEmail, normalizeUSPhone } from "../identity/normalize";
import type {
  AppSettings,
  AuditCallRow,
  ConnectionRow,
  ContactRow,
  DailyPrioritiesRow,
  HarvestConvRow,
  HarvestProgressRow,
  LeadCountAdjustmentRow,
  ManualOverrideRow,
  OpportunityRow,
  RepGoalRowFull,
  Store,
  SyncRunRow,
  TeamGoalRow,
  UserRow,
} from "./types";
import { DEFAULT_CALL_START_DATES, defaultSettings, normalizeAppSettings } from "./types";

interface CallExt extends CallRow {
  external_call_id: string;
  provider: string;
}
interface ApptExt extends AppointmentRow {
  acuity_appointment_id: string;
  client_name?: string | null;
  client_phone?: string | null;
  client_email?: string | null;
}
interface LeadExt extends LeadRow {
  source_id: string;
  provider: string;
  name?: string | null;
  phone?: string | null;
  email?: string | null;
}
interface BlockedExt extends BlockedTimeRow {
  provider: string;
  external_id: string;
}

export class MemoryStore implements Store {
  mode = "memory" as const;

  private settings: AppSettings = defaultSettings();
  private users = new Map<string, UserRow>();
  private contacts = new Map<string, ContactRow>();
  private calls = new Map<string, CallExt>(); // keyed by provider:external_call_id
  private harvestProgress = new Map<string, HarvestProgressRow>();
  private harvestConvs = new Map<string, HarvestConvRow & { visited: boolean; calls_found: number; messages_scanned: number }>();
  private opportunities = new Map<string, OpportunityRow>(); // keyed by provider:external_id
  private appointments = new Map<string, ApptExt>(); // keyed by acuity_appointment_id
  private attributions = new Map<string, AttributionRow>(); // keyed by appointment_id
  private leads = new Map<string, LeadExt>(); // keyed by sheet:source_id
  private availabilityRules: AvailabilityRule[] = [];
  private blocked = new Map<string, BlockedExt>();
  private teamGoals = new Map<string, TeamGoalRow>();
  private repGoals = new Map<string, RepGoalRowFull>();
  private connections = new Map<string, ConnectionRow>();
  private syncRuns: SyncRunRow[] = [];
  private watermarks = new Map<string, string>();
  private overrides: ManualOverrideRow[] = [];
  private dailyPriorities = new Map<string, DailyPrioritiesRow>();
  private leadAdjustments = new Map<string, LeadCountAdjustmentRow>(); // keyed work_date:sheet
  private seq = 0;

  private nextId(prefix: string): string {
    this.seq += 1;
    return `${prefix}_${this.seq}`;
  }

  private schemaDone = false;

  async ensureSchema(): Promise<void> {
    // Mirror the PG store's memoized DDL: the owner-set activation-date
    // backfill runs ONCE per store lifetime (Dan McKillop begins calling
    // 2026-09-28) so the Settings editor can later clear a date without it
    // snapping back on the next read.
    if (this.schemaDone) return;
    this.schemaDone = true;
    for (const u of this.users.values()) {
      if (u.call_start_date == null && DEFAULT_CALL_START_DATES[u.name]) {
        u.call_start_date = DEFAULT_CALL_START_DATES[u.name];
      }
    }
  }

  async getSettings(): Promise<AppSettings> {
    // Normalize on read so settings saved before newer default fields existed
    // (e.g. sheets.<sheet>.mode) still see those defaults.
    return normalizeAppSettings(this.settings);
  }
  async saveSettings(patch: Partial<AppSettings>): Promise<AppSettings> {
    this.settings = {
      ...this.settings,
      ...patch,
      studio: { ...this.settings.studio, ...(patch.studio ?? {}) },
      sheets: { ...this.settings.sheets, ...(patch.sheets ?? {}) },
      acuity: { ...this.settings.acuity, ...(patch.acuity ?? {}) },
    };
    return JSON.parse(JSON.stringify(this.settings));
  }

  async upsertTeamGoal(row: TeamGoalRow): Promise<void> {
    this.teamGoals.set(row.week_start, { ...row });
  }
  async getTeamGoal(weekStart: string): Promise<TeamGoalRow | null> {
    return this.teamGoals.get(weekStart) ?? null;
  }
  async getTeamGoals(): Promise<TeamGoalRow[]> {
    return [...this.teamGoals.values()].sort((a, b) => (a.week_start < b.week_start ? -1 : 1));
  }
  async upsertRepGoals(rows: RepGoalRowFull[]): Promise<void> {
    for (const r of rows) this.repGoals.set(`${r.rep_id}:${r.week_start}`, { ...r });
  }
  async getRepGoals(weekStart: string): Promise<RepGoalRowFull[]> {
    return [...this.repGoals.values()].filter((r) => r.week_start === weekStart);
  }
  async deleteRepGoal(repId: string, weekStart: string): Promise<void> {
    this.repGoals.delete(`${repId}:${weekStart}`);
  }

  async upsertUsers(rows: UserRow[]): Promise<number> {
    for (const r of rows) {
      const existing = [...this.users.values()].find((u) => u.provider === r.provider && u.external_id === r.external_id);
      if (existing) this.users.set(existing.id, { ...existing, ...r, id: existing.id, call_start_date: r.call_start_date ?? existing.call_start_date ?? null });
      else {
        const key = this.nextId("u");
        this.users.set(key, { ...r, id: key, call_start_date: r.call_start_date ?? null });
      }
    }
    return rows.length;
  }
  async setUserCallStartDate(repId: string, date: string | null): Promise<void> {
    const u = this.users.get(repId);
    if (u) this.users.set(repId, { ...u, call_start_date: date });
  }
  async getUsers(): Promise<UserRow[]> {
    await this.ensureSchema();
    // Active-roster users only — same semantics as the PG store's read.
    return [...this.users.values()].filter((u) => u.is_active);
  }
  async getAllUsers(): Promise<UserRow[]> {
    await this.ensureSchema();
    return [...this.users.values()];
  }

  async upsertContacts(rows: ContactRow[]): Promise<number> {
    for (const r of rows) {
      // Mirror of the PG store: raw values verbatim, canonical identity keys
      // derived at the boundary when not supplied, upsert-only (never delete).
      const patch: ContactRow = {
        ...r,
        phone_raw: r.phone_raw ?? r.phone,
        email_raw: r.email_raw ?? r.email,
        phone_normalized: r.phone_normalized ?? normalizeUSPhone(r.phone),
        email_normalized: r.email_normalized ?? normalizeEmail(r.email),
      };
      const existing = [...this.contacts.values()].find((c) => c.provider === r.provider && c.external_id === r.external_id);
      if (existing) {
        this.contacts.set(existing.id, {
          ...existing,
          ...patch,
          id: existing.id,
          name: patch.name ?? existing.name,
          assigned_rep_id: patch.assigned_rep_id ?? existing.assigned_rep_id,
          first_name: patch.first_name ?? existing.first_name ?? null,
          last_name: patch.last_name ?? existing.last_name ?? null,
          phone_raw: patch.phone_raw ?? existing.phone_raw ?? null,
          phone_normalized: patch.phone_normalized ?? existing.phone_normalized ?? null,
          email_raw: patch.email_raw ?? existing.email_raw ?? null,
          email_normalized: patch.email_normalized ?? existing.email_normalized ?? null,
          source_created_at: patch.source_created_at ?? existing.source_created_at ?? null,
          source_updated_at: patch.source_updated_at ?? existing.source_updated_at ?? null,
          last_synced_at: patch.last_synced_at ?? existing.last_synced_at ?? null,
        });
      } else {
        const key = this.nextId("c");
        this.contacts.set(key, { ...patch, id: key, created_at: r.created_at ?? new Date().toISOString() });
      }
    }
    return rows.length;
  }
  async getContacts(): Promise<ContactRow[]> {
    return [...this.contacts.values()];
  }

  async upsertCalls(rows: CallExt[]): Promise<number> {
    for (const r of rows) {
      const key = `${r.provider}:${r.external_call_id}`;
      const existing = this.calls.get(key);
      // keep stable internal id across re-syncs
      this.calls.set(key, { ...r, id: existing?.id ?? this.nextId("call") });
    }
    return rows.length;
  }
  async getCallsBetween(startUtc: string, endUtc: string): Promise<CallRow[]> {
    return [...this.calls.values()]
      .filter((c) => c.started_at >= startUtc && c.started_at < endUtc)
      .map(({ provider: _p, ...rest }) => rest); // external_call_id now CARRIED (attribution engine reads it)
  }
  async getAllCallsSince(startUtc: string): Promise<CallRow[]> {
    return this.getCallsBetween(startUtc, "9999-12-31");
  }
  async getAuditCalls(startUtc: string, endUtc: string, repSpec: string | null, thresholdSeconds: number): Promise<AuditCallRow[]> {
    // Same semantics as the PG store (see its ownership comment): bucket specs
    // "non-roster" (owner KNOWN and outside the active roster — via rep_id
    // linkage OR resolved from the raw HL user id) / "unattributed" (no
    // determinable owner: rep NULL and the raw HL user id missing or
    // unresolved) / "unassigned" (legacy alias = union of both),
    // over_threshold per live threshold.
    await this.ensureSchema();
    const activeIds = new Set([...this.users.values()].filter((u) => u.is_active).map((u) => u.id));
    type CallAuditExt = CallExt & { conversation_id?: string | null; provider_rep_external_id?: string | null };
    const hlUserByKey = new Map([...this.users.values()].map((u) => [`${u.provider}:${u.external_id}`, u]));
    // Owner of one row: rep_id linkage first, else the raw provider user id.
    const ownerOf = (c: CallAuditExt): { id: string | null; name: string | null; isActive: boolean | null } => {
      if (c.rep_id !== null) {
        const u = this.users.get(c.rep_id);
        return { id: c.rep_id, name: u?.name ?? null, isActive: u ? u.is_active : false }; // dangling → treated non-roster
      }
      const prov = c.provider_rep_external_id ?? null;
      if (!prov) return { id: null, name: null, isActive: null };
      const pu = hlUserByKey.get(`${c.provider}:${prov}`) ?? null;
      return pu ? { id: pu.id, name: pu.name, isActive: pu.is_active } : { id: null, name: null, isActive: null };
    };
    const isNonRoster = (c: CallAuditExt): boolean => {
      const o = ownerOf(c);
      return o.id !== null && !activeIds.has(o.id);
    };
    const isUnattributed = (c: CallAuditExt): boolean => {
      if (c.rep_id !== null) return false;
      return ownerOf(c).id === null; // no prov, or prov resolves to no user row
    };
    const rows = [...this.calls.values()]
      .filter((c) => c.started_at >= startUtc && c.started_at < endUtc)
      .filter((c) => {
        if (!repSpec || repSpec === "all") return true;
        if (repSpec === "non-roster") return isNonRoster(c as CallAuditExt);
        if (repSpec === "unattributed") return isUnattributed(c as CallAuditExt);
        if (repSpec === "unassigned") return isNonRoster(c as CallAuditExt) || isUnattributed(c as CallAuditExt);
        return c.rep_id === repSpec;
      })
      .sort((a, b) => (a.started_at < b.started_at ? 1 : a.started_at > b.started_at ? -1 : a.external_call_id < b.external_call_id ? 1 : -1));
    return rows.map((c) => {
      const cx = c as CallAuditExt;
      const linked = c.rep_id ? this.users.get(c.rep_id) : undefined;
      const contact = c.contact_id ? this.contacts.get(c.contact_id) : undefined;
      const owner = ownerOf(cx);
      return {
        external_call_id: c.external_call_id,
        conversation_id: cx.conversation_id ?? null,
        rep_id: c.rep_id ?? null,
        // Raw linkage first; rows resolved from the raw HL user id show that
        // owner's name/state so Non Roster Calls are human-readable.
        rep_name: linked?.name ?? owner.name,
        rep_is_active: linked ? linked.is_active : owner.isActive,
        provider_rep_external_id: cx.provider_rep_external_id ?? null,
        contact_id: c.contact_id ?? null,
        contact_name: contact?.name ?? null,
        contact_external_id: contact?.external_id ?? null,
        direction: (c as Partial<CallRow> & { direction?: string | null }).direction ?? null,
        call_status: (c as Partial<CallRow> & { call_status?: string | null }).call_status ?? null,
        started_at: c.started_at,
        duration_seconds: c.duration_seconds,
        over_threshold: c.duration_seconds > thresholdSeconds,
      };
    });
  }

  async upsertOpportunities(rows: OpportunityRow[]): Promise<number> {
    for (const r of rows) {
      const key = `${r.provider}:${r.external_id}`;
      const existing = this.opportunities.get(key);
      this.opportunities.set(key, { ...r, id: existing?.id ?? this.nextId("opp") });
    }
    return rows.length;
  }
  async getOpportunities(): Promise<OpportunityRow[]> {
    return [...this.opportunities.values()];
  }

  /** Mirror of the PG store's demo-content replacement (see Store doc). */
  async deleteDemoHighLevelRows(): Promise<{ users: number; contacts: number; calls: number }> {
    const isDemoRow = (externalId: string | undefined) => typeof externalId === "string" && externalId.startsWith("demo-");
    let users = 0;
    let contacts = 0;
    let calls = 0;
    // attribution rows keep history: demo call links are nulled, rows stay
    const demoCallInternalIds = new Set(
      [...this.calls.values()].filter((c) => c.provider === "highlevel" && isDemoRow(c.external_call_id)).map((c) => c.id),
    );
    for (const [key, a] of this.attributions) {
      if (a.call_id && demoCallInternalIds.has(a.call_id)) this.attributions.set(key, { ...a, call_id: null });
    }
    for (const [key, c] of this.calls) {
      if (c.provider === "highlevel" && isDemoRow(c.external_call_id)) {
        this.calls.delete(key);
        calls += 1;
      }
    }
    const demoUserIds = new Set([...this.users.values()].filter((u) => u.provider === "highlevel" && isDemoRow(u.external_id)).map((u) => u.id));
    const demoContactIds = new Set([...this.contacts.values()].filter((c) => c.provider === "highlevel" && isDemoRow(c.external_id)).map((c) => c.id));
    for (const [key, a] of this.appointments) if (a.contact_id && demoContactIds.has(a.contact_id)) this.appointments.set(key, { ...a, contact_id: null });
    for (const [key, l] of this.leads) {
      const patch: Partial<LeadExt> = {};
      if (l.contact_id && demoContactIds.has(l.contact_id)) patch.contact_id = null;
      if (l.assigned_rep_id && demoUserIds.has(l.assigned_rep_id)) patch.assigned_rep_id = null;
      if (Object.keys(patch).length) this.leads.set(key, { ...l, ...patch });
    }
    for (const [key, o] of this.opportunities) {
      const patch: Partial<OpportunityRow> = {};
      if (o.contact_id && demoContactIds.has(o.contact_id)) patch.contact_id = null;
      if (o.rep_id && demoUserIds.has(o.rep_id)) patch.rep_id = null;
      if (Object.keys(patch).length) this.opportunities.set(key, { ...o, ...patch });
    }
    for (const c of this.contacts.values()) if (c.assigned_rep_id && demoUserIds.has(c.assigned_rep_id)) c.assigned_rep_id = null;
    for (const [key, c] of this.contacts) {
      if (c.provider === "highlevel" && isDemoRow(c.external_id)) {
        this.contacts.delete(key);
        contacts += 1;
      }
    }
    for (const key of [...this.repGoals.keys()]) if (demoUserIds.has(key.split(":")[0])) this.repGoals.delete(key);
    for (const [key, u] of this.users) {
      if (u.provider === "highlevel" && isDemoRow(u.external_id)) {
        this.users.delete(key);
        users += 1;
      }
    }
    return { users, contacts, calls };
  }

  async upsertAppointments(rows: ApptExt[]): Promise<number> {
    for (const r of rows) {
      const existing = this.appointments.get(r.acuity_appointment_id);
      // keep stable internal id across re-syncs; cancellations update in place
      this.appointments.set(r.acuity_appointment_id, {
        ...r,
        id: existing?.id ?? this.nextId("appt"),
      });
    }
    return rows.length;
  }
  private stripAppt(a: ApptExt): AppointmentRow {
    const { acuity_appointment_id: _a, client_name: _n, client_phone: _p, client_email: _e, ...rest } = a;
    return rest;
  }
  async getAppointmentsCreatedBetween(startUtc: string, endUtc: string): Promise<AppointmentRow[]> {
    return [...this.appointments.values()]
      .filter((a) => a.created_at >= startUtc && a.created_at < endUtc)
      .map((a) => this.stripAppt(a));
  }
  async getAppointmentsOverlapping(startUtc: string, endUtc: string): Promise<AppointmentRow[]> {
    // Availability path — mirrors pg.ts: carries the per-appointment duration,
    // calendar name (scope matching), acuity id AND the client contact fields
    // (the attribution engine's phone/email tiers read them from this selector).
    return [...this.appointments.values()]
      .filter((a) => a.appointment_datetime < endUtc && a.appointment_datetime >= startUtc)
      .map((a) => ({
        ...this.stripAppt(a),
        calendar_name: a.calendar_name ?? null,
        acuity_appointment_id: a.acuity_appointment_id,
        duration_minutes: a.duration_minutes ?? null,
        client_name: a.client_name ?? null,
        client_phone: a.client_phone ?? null,
        client_email: a.client_email ?? null,
      }));
  }
  async getAllAppointmentsSince(startUtc: string): Promise<AppointmentRow[]> {
    return [...this.appointments.values()]
      .filter((a) => a.appointment_datetime >= startUtc || a.created_at >= startUtc)
      .map((a) => this.stripAppt(a));
  }
  async getAppointmentsWithClientsSince(startUtc: string): Promise<(AppointmentRow & {
    acuity_appointment_id: string | null;
    client_name: string | null;
    client_phone: string | null;
    client_email: string | null;
    calendar_name: string | null;
  })[]> {
    return [...this.appointments.values()]
      .filter((a) => a.appointment_datetime >= startUtc || a.created_at >= startUtc)
      .map((a) => ({
        ...this.stripAppt(a),
        acuity_appointment_id: a.acuity_appointment_id,
        client_name: a.client_name ?? null,
        client_phone: a.client_phone ?? null,
        client_email: a.client_email ?? null,
        calendar_name: (a as unknown as { calendar_name?: string | null }).calendar_name ?? null,
      }));
  }

  async upsertAttributions(rows: AttributionRow[]): Promise<number> {
    for (const r of rows) {
      // mirror the PG store: never overwrite a manual override automatically
      const existing = this.attributions.get(r.appointment_id);
      if (existing?.manual_override) continue;
      this.attributions.set(r.appointment_id, { ...r });
    }
    return rows.length;
  }
  async getAttributions(): Promise<AttributionRow[]> {
    return [...this.attributions.values()];
  }
  async setManualAttribution(row: AttributionRow): Promise<void> {
    // manual assignment wins over the engine and survives re-syncs (engine
    // upserts skip rows with manual_override = true)
    this.attributions.set(row.appointment_id, { ...row, method: "manual", manual_override: true });
  }
  async deleteAttribution(appointmentId: string): Promise<void> {
    // manual UNASSIGN: mirror the PG store — delete the derived row; the next
    // attribution tick recomputes the appointment from raw rows
    this.attributions.delete(appointmentId);
  }

  async deleteLeadsForSheet(sourceSheet: string): Promise<void> {
    for (const [key, lead] of this.leads) {
      if (lead.provider === "google_sheets" && lead.source_sheet === sourceSheet) this.leads.delete(key);
    }
  }
  async upsertLeads(rows: LeadExt[]): Promise<number> {
    for (const r of rows) {
      const key = `${r.provider}:${r.source_id}`;
      const existing = this.leads.get(key);
      this.leads.set(key, { ...r, id: existing?.id ?? this.nextId("lead") });
    }
    return rows.length;
  }
  async getLeadsByWorkDates(dates: string[]): Promise<LeadRow[]> {
    const set = new Set(dates);
    return [...this.leads.values()]
      .filter((l) => set.has(l.work_date))
      .map(({ source_id: _s, provider: _p, name: _n, phone: _p2, email: _e, ...rest }) => rest);
  }
  async updateLeadWorkDate(id: string, workDate: string): Promise<void> {
    for (const [key, lead] of this.leads) {
      if (lead.id === id) {
        this.leads.set(key, { ...lead, work_date: workDate });
        return;
      }
    }
    throw new Error(`Lead ${id} not found`);
  }

  async upsertLeadCountAdjustment(row: Omit<LeadCountAdjustmentRow, "updated_at">): Promise<void> {
    if (!row.delta) {
      // corrected back to the observed count → the adjustment disappears
      this.leadAdjustments.delete(`${row.work_date}:${row.sheet}`);
      return;
    }
    this.leadAdjustments.set(`${row.work_date}:${row.sheet}`, { ...row, updated_at: new Date().toISOString() });
  }
  async getLeadCountAdjustments(dates: string[]): Promise<LeadCountAdjustmentRow[]> {
    const set = new Set(dates);
    return [...this.leadAdjustments.values()].filter((a) => set.has(a.work_date));
  }

  async upsertAvailabilityRules(rows: AvailabilityRule[]): Promise<void> {
    this.availabilityRules = rows.map((r) => ({ ...r }));
  }
  async getAvailabilityRules(): Promise<AvailabilityRule[]> {
    return this.availabilityRules.map((r) => ({ ...r }));
  }
  async upsertBlockedTimes(rows: BlockedExt[]): Promise<number> {
    for (const r of rows) this.blocked.set(`${r.provider}:${r.external_id}`, { ...r });
    return rows.length;
  }
  async deleteDemoAcuityRows(): Promise<{ appointments: number; blocked: number }> {
    // Mirror pg.ts: drop the demo generator's Acuity appointments (ids
    // prefixed "demo-") + demo blocked rows (provider acuity); manual blocks
    // and recurring blocks stay. Idempotent.
    let appointments = 0;
    for (const [key, a] of this.appointments) {
      if (a.acuity_appointment_id.startsWith("demo-")) {
        this.appointments.delete(key);
        appointments += 1;
      }
    }
    let blocked = 0;
    for (const [key, b] of this.blocked) {
      if (b.provider === "acuity" && b.external_id.startsWith("demo-")) {
        this.blocked.delete(key);
        blocked += 1;
      }
    }
    return { appointments, blocked };
  }
  async getBlockedTimesBetween(startUtc: string, endUtc: string): Promise<BlockedTimeRow[]> {
    return [...this.blocked.values()]
      .filter((b) => b.end_at > startUtc && b.start_at < endUtc)
      .map(({ provider: _p, external_id: _e, ...rest }) => rest);
  }
  async insertBlockedTime(row: { start_at: string; end_at: string; reason: string | null }): Promise<BlockedTimeRow> {
    const id = this.nextId("block");
    this.blocked.set(`manual:${id}`, {
      provider: "manual",
      external_id: id,
      id,
      start_at: row.start_at,
      end_at: row.end_at,
      reason: row.reason,
    });
    return { id, start_at: row.start_at, end_at: row.end_at, reason: row.reason };
  }
  async deleteBlockedTime(id: string): Promise<void> {
    for (const [key, block] of this.blocked) {
      if (block.id === id) {
        this.blocked.delete(key);
        return;
      }
    }
  }

  async upsertDailyPriorities(row: DailyPrioritiesRow): Promise<void> {
    this.dailyPriorities.set(row.date, { ...row });
  }
  async getDailyPriorities(date: string): Promise<DailyPrioritiesRow | null> {
    return this.dailyPriorities.get(date) ?? null;
  }

  async upsertConnection(row: ConnectionRow): Promise<void> {
    this.connections.set(row.provider, { ...row });
  }
  async getConnections(): Promise<ConnectionRow[]> {
    return [...this.connections.values()];
  }

  async insertSyncRun(provider: string): Promise<string> {
    const id = this.nextId("sync");
    this.syncRuns.push({ id, provider, status: "running", started_at: new Date().toISOString(), finished_at: null, records_upserted: 0, error: null });
    return id;
  }
  async finishSyncRun(id: string, status: string, recordsUpserted: number, error: string | null): Promise<void> {
    const run = this.syncRuns.find((r) => r.id === id);
    if (run) {
      run.status = status;
      run.records_upserted = recordsUpserted;
      run.error = error;
      run.finished_at = new Date().toISOString();
    }
  }
  async getSyncRuns(limit: number): Promise<SyncRunRow[]> {
    return this.syncRuns.slice(-limit).reverse();
  }
  async getRunningSyncRun(provider: string): Promise<SyncRunRow | null> {
    const running = this.syncRuns.filter((r) => r.provider === provider && r.status === "running" && r.finished_at === null);
    return running.length ? running[running.length - 1] : null;
  }
  async getSyncWatermark(provider: string): Promise<string | null> {
    return this.watermarks.get(provider) ?? null;
  }
  async setSyncWatermark(provider: string, watermarkIso: string): Promise<void> {
    this.watermarks.set(provider, watermarkIso);
  }
  private checkpoints = new Map<string, string>();
  async getSyncCheckpoint(key: string): Promise<string | null> {
    return this.checkpoints.get(key) ?? null;
  }
  async setSyncCheckpoint(key: string, value: string): Promise<void> {
    this.checkpoints.set(key, value);
  }

  async insertManualOverride(row: Omit<ManualOverrideRow, "id" | "changed_at">): Promise<void> {
    this.overrides.push({ ...row, id: this.nextId("ovr"), changed_at: new Date().toISOString() });
  }
  async getManualOverrides(limit: number): Promise<ManualOverrideRow[]> {
    return this.overrides.slice(-limit).reverse();
  }

  // ---- call harvest (resumable; mirrors PgStore semantics) ----
  async getHarvestProgress(id = "highlevel-calls"): Promise<HarvestProgressRow | null> {
    const p = this.harvestProgress.get(id);
    return p ? { ...p } : null;
  }
  async saveHarvestProgress(p: HarvestProgressRow): Promise<void> {
    this.harvestProgress.set(p.id, { ...p });
  }
  async upsertHarvestConversations(rows: HarvestConvRow[]): Promise<number> {
    for (const r of rows) {
      const prev = this.harvestConvs.get(r.conv_id);
      if (prev) {
        this.harvestConvs.set(r.conv_id, {
          ...r,
          message_types: [...new Set([...prev.message_types, ...r.message_types])],
          last_message_type: r.last_message_type ?? prev.last_message_type,
          contact_id: r.contact_id ?? prev.contact_id,
          assigned_to: r.assigned_to ?? prev.assigned_to,
          visited: prev.visited,
          calls_found: prev.calls_found,
          messages_scanned: prev.messages_scanned,
        });
      } else {
        this.harvestConvs.set(r.conv_id, { ...r, visited: false, calls_found: 0, messages_scanned: 0 });
      }
    }
    return rows.length;
  }
  async getUnvisitedInWindow(windowStartMs: number, limit: number, callFlaggedFirst: boolean): Promise<HarvestConvRow[]> {
    const rows = [...this.harvestConvs.values()]
      .filter((c) => !c.visited && c.last_message_date >= windowStartMs);
    const flagged = (c: (typeof rows)[number]) => c.message_types.includes(1) || c.last_message_type === "TYPE_CALL" ? 1 : 0;
    rows.sort((a, b) => (callFlaggedFirst ? flagged(b) - flagged(a) : 0) || b.last_message_date - a.last_message_date);
    return rows.slice(0, limit).map(({ visited, calls_found, messages_scanned, ...r }) => r);
  }
  async markHarvestVisited(convIds: string[], callsFoundByConv: Record<string, number>, messagesScannedByConv?: Record<string, number>): Promise<void> {
    for (const id of convIds) {
      const prev = this.harvestConvs.get(id);
      if (prev) {
        this.harvestConvs.set(id, {
          ...prev,
          visited: true,
          calls_found: callsFoundByConv[id] ?? 0,
          messages_scanned: prev.messages_scanned + (messagesScannedByConv?.[id] ?? 0),
        });
      }
    }
  }
  async getHarvestCoverageSummary(windowStartMs: number): Promise<{ total: number; visited: number; callFlagged: number; byDay: { day: string; total: number; visited: number }[] }> {
    const inWindow = [...this.harvestConvs.values()].filter((c) => c.last_message_date >= windowStartMs);
    const etDay = (ms: number): string => new Intl.DateTimeFormat("en-CA", { timeZone: "America/New_York" }).format(new Date(ms));
    const byDay = new Map<string, { total: number; visited: number }>();
    for (const c of inWindow) {
      const day = etDay(c.last_message_date);
      const cur = byDay.get(day) ?? { total: 0, visited: 0 };
      cur.total += 1;
      if (c.visited) cur.visited += 1;
      byDay.set(day, cur);
    }
    return {
      total: inWindow.length,
      visited: inWindow.filter((c) => c.visited).length,
      callFlagged: inWindow.filter((c) => c.message_types.includes(1) || c.last_message_type === "TYPE_CALL").length,
      byDay: [...byDay.entries()].sort((a, b) => (a[0] < b[0] ? 1 : -1)).map(([day, v]) => ({ day, ...v })),
    };
  }
}
